            version: "0.2"
            phases:
            pre_build:
            commands:
            - echo Logging in to Amazon ECR...
            - aws --version
            - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
            - REPOSITORY_URI=931728113463.dkr.ecr.us-east-2.amazonaws.com/newyaml
    build: .
    restart: on-failure
    env_file:
      - ./.env
         commands: 
        - python manage.py runserver 0.0.0.0:8000
        - echo Build started on `date`
        - echo Building the Docker image...
        - docker build -t $REPOSITORY_URI:latest .
    volumes:
      - .:/www
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: "postgres:10.3-alpine"
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    post_build:
          commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
